# vim: set et ts=4 sw=4: -*- mode: yaml-mode; yaml-indent-offset: 4 -*-
base_url: https://gerrit.wikimedia.org/r/
bundles:
    base:
        - "mediawiki/extensions/CategoryTree"
        - "mediawiki/extensions/Cite"
        - "mediawiki/extensions/CiteThisPage"
        - "mediawiki/extensions/CodeEditor"
        - "mediawiki/extensions/ConfirmEdit"
        - "mediawiki/extensions/Gadgets"
        - "mediawiki/extensions/ImageMap"
        - "mediawiki/extensions/InputBox"
        - "mediawiki/extensions/Interwiki"
        - "mediawiki/extensions/LocalisationUpdate"
        - "mediawiki/extensions/MultimediaViewer"
        - "mediawiki/extensions/Nuke"
        - "mediawiki/extensions/OATHAuth"
        - "mediawiki/extensions/PageImages"
        - "mediawiki/extensions/ParserFunctions"
        - "mediawiki/extensions/PdfHandler"
        - "mediawiki/extensions/Poem"
        - "mediawiki/extensions/Renameuser"
        - "mediawiki/extensions/ReplaceText"
        - "mediawiki/extensions/Scribunto"
        - "mediawiki/extensions/SecureLinkFixer"
        - "mediawiki/extensions/SpamBlacklist"
        - "mediawiki/extensions/SyntaxHighlight_GeSHi"
        - "mediawiki/extensions/TemplateData"
        - "mediawiki/extensions/TextExtracts"
        - "mediawiki/extensions/TitleBlacklist"
        - "mediawiki/extensions/VisualEditor"
        - "mediawiki/extensions/WikiEditor"
        - "mediawiki/skins/MonoBook"
        - "mediawiki/skins/Timeless"
        - "mediawiki/skins/Vector"
        - "mediawiki/vendor"
    wmf_core:
        - "mediawiki/extensions/3D"
        - "mediawiki/extensions/AbuseFilter"
        - "mediawiki/extensions/ActiveAbstract"
        - "mediawiki/extensions/AdvancedSearch"
        - "mediawiki/extensions/AntiSpoof"
        - "mediawiki/extensions/ApiFeatureUsage"
        - "mediawiki/extensions/ArticleCreationWorkflow"
        - "mediawiki/extensions/ArticlePlaceholder"
        - "mediawiki/extensions/Babel"
        - "mediawiki/extensions/BetaFeatures"
        - "mediawiki/extensions/BounceHandler"
        - "mediawiki/extensions/Calendar"
        - "mediawiki/extensions/Campaigns"
        - "mediawiki/extensions/Capiunto"
        - "mediawiki/extensions/CategoryTree"
        - "mediawiki/extensions/CentralAuth"
        - "mediawiki/extensions/CentralNotice"
        - "mediawiki/extensions/CharInsert"
        - "mediawiki/extensions/CheckUser"
        - "mediawiki/extensions/ChessBrowser"
        - "mediawiki/extensions/CirrusSearch"
        - "mediawiki/extensions/Cite"
        - "mediawiki/extensions/CiteThisPage"
        - "mediawiki/extensions/Citoid"
        - "mediawiki/extensions/cldr"
        - "mediawiki/extensions/CodeEditor"
        - "mediawiki/extensions/CodeMirror"
        - "mediawiki/extensions/CodeReview"
        - "mediawiki/extensions/Cognate"
        - "mediawiki/extensions/Collection"
        - "mediawiki/extensions/CommonsMetadata"
        - "mediawiki/extensions/ConfirmEdit"
        - "mediawiki/extensions/CongressLookup"
        - "mediawiki/extensions/ContactPage"
        - "mediawiki/extensions/ContentTranslation"
        - "mediawiki/extensions/CreditsSource"
        - "mediawiki/extensions/Dashiki"
        - "mediawiki/extensions/Disambiguator"
        - "mediawiki/extensions/DiscussionTools"
        - "mediawiki/extensions/DismissableSiteNotice"
        - "mediawiki/extensions/DonationInterface"
        - "mediawiki/extensions/DoubleWiki"
        - "mediawiki/extensions/DynamicSidebar"
        - "mediawiki/extensions/Echo"
        - "mediawiki/extensions/Elastica"
        - "mediawiki/extensions/ElectronPdfService"
        - "mediawiki/extensions/EntitySchema"
        - "mediawiki/extensions/EventBus"
        - "mediawiki/extensions/EventLogging"
        - "mediawiki/extensions/EventStreamConfig"
        - "mediawiki/extensions/ExtensionDistributor"
        - "mediawiki/extensions/ExternalGuidance"
        - "mediawiki/extensions/FeaturedFeeds"
        - "mediawiki/extensions/FileExporter"
        - "mediawiki/extensions/FileImporter"
        - "mediawiki/extensions/FlaggedRevs"
        - "mediawiki/extensions/Flow"
        - "mediawiki/extensions/FundraiserLandingPage"
        - "mediawiki/extensions/FundraisingTranslateWorkflow"
        - "mediawiki/extensions/Gadgets"
        - "mediawiki/extensions/GeoCrumbs"
        - "mediawiki/extensions/GeoData"
        - "mediawiki/extensions/GettingStarted"
        - "mediawiki/extensions/GlobalBlocking"
        - "mediawiki/extensions/GlobalCssJs"
        - "mediawiki/extensions/GlobalPreferences"
        - "mediawiki/extensions/GlobalUsage"
        - "mediawiki/extensions/GlobalUserPage"
        - "mediawiki/extensions/GlobalWatchlist"
        - "mediawiki/extensions/GoogleNewsSitemap"
        - "mediawiki/extensions/Graph"
        - "mediawiki/extensions/GrowthExperiments"
        - "mediawiki/extensions/GuidedTour"
        - "mediawiki/extensions/GWToolset"
        - "mediawiki/extensions/ImageMap"
        - "mediawiki/extensions/InputBox"
        - "mediawiki/extensions/Insider"
        - "mediawiki/extensions/intersection"
        - "mediawiki/extensions/Interwiki"
        - "mediawiki/extensions/InterwikiSorting"
        - "mediawiki/extensions/IPInfo"
        - "mediawiki/extensions/Josa"
        - "mediawiki/extensions/JsonConfig"
        - "mediawiki/extensions/Kartographer"
        - "mediawiki/extensions/LabeledSectionTransclusion"
        - "mediawiki/extensions/LandingCheck"
        - "mediawiki/extensions/LdapAuthentication"
        - "mediawiki/extensions/Linter"
        - "mediawiki/extensions/LiquidThreads"
        - "mediawiki/extensions/Listings"
        - "mediawiki/extensions/LocalisationUpdate"
        - "mediawiki/extensions/LoginNotify"
        - "mediawiki/extensions/MachineVision"
        - "mediawiki/extensions/MapSources"
        - "mediawiki/extensions/MassMessage"
        - "mediawiki/extensions/Math"
        - "mediawiki/extensions/MediaModeration"
        - "mediawiki/extensions/MediaSearch"
        - "mediawiki/extensions/MobileApp"
        - "mediawiki/extensions/MobileFrontend"
        - "mediawiki/extensions/MultimediaViewer"
        - "mediawiki/extensions/NavigationTiming"
        - "mediawiki/extensions/NearbyPages"
        - "mediawiki/extensions/Newsletter"
        - "mediawiki/extensions/NewUserMessage"
        - "mediawiki/extensions/Nuke"
        - "mediawiki/extensions/OATHAuth"
        - "mediawiki/extensions/OAuth"
        - "mediawiki/extensions/OAuthRateLimiter"
        - "mediawiki/extensions/OpenStackManager"
        - "mediawiki/extensions/ORES"
        - "mediawiki/extensions/PageAssessments"
        - "mediawiki/extensions/PagedTiffHandler"
        - "mediawiki/extensions/PageImages"
        - "mediawiki/extensions/PageNotice"
        - "mediawiki/extensions/PageTriage"
        - "mediawiki/extensions/PageViewInfo"
        - "mediawiki/extensions/ParserFunctions"
        - "mediawiki/extensions/PdfHandler"
        - "mediawiki/extensions/Poem"
        - "mediawiki/extensions/PoolCounter"
        - "mediawiki/extensions/Popups"
        - "mediawiki/extensions/ProofreadPage"
        - "mediawiki/extensions/PropertySuggester"
        - "mediawiki/extensions/QuickSurveys"
        - "mediawiki/extensions/Quiz"
        - "mediawiki/extensions/ReadingLists"
        - "mediawiki/extensions/RelatedArticles"
        - "mediawiki/extensions/Renameuser"
        - "mediawiki/extensions/RevisionSlider"
        - "mediawiki/extensions/RSS"
        - "mediawiki/extensions/SandboxLink"
        - "mediawiki/extensions/Score"
        - "mediawiki/extensions/Scribunto"
        - "mediawiki/extensions/SearchExtraNS"
        - "mediawiki/extensions/SecureLinkFixer"
        - "mediawiki/extensions/SecurePoll"
        - "mediawiki/extensions/ShortUrl"
        - "mediawiki/extensions/SiteMatrix"
        - "mediawiki/extensions/SpamBlacklist"
        - "mediawiki/extensions/StopForumSpam"
        - "mediawiki/extensions/SubPageList3"
        - "mediawiki/extensions/SubpageSortkey"
        - "mediawiki/extensions/SyntaxHighlight_GeSHi"
        - "mediawiki/extensions/TemplateData"
        - "mediawiki/extensions/TemplateSandbox"
        - "mediawiki/extensions/TemplateStyles"
        - "mediawiki/extensions/TemplateWizard"
        - "mediawiki/extensions/TextExtracts"
        - "mediawiki/extensions/Thanks"
        - "mediawiki/extensions/TheWikipediaLibrary"
        - "mediawiki/extensions/TimedMediaHandler"
        - "mediawiki/extensions/timeline"
        - "mediawiki/extensions/TitleBlacklist"
        - "mediawiki/extensions/TocTree"
        - "mediawiki/extensions/TorBlock"
        - "mediawiki/extensions/Translate"
        - "mediawiki/extensions/TranslationNotifications"
        - "mediawiki/extensions/TrustedXFF"
        - "mediawiki/extensions/TwoColConflict"
        - "mediawiki/extensions/UniversalLanguageSelector"
        - "mediawiki/extensions/UploadsLink"
        - "mediawiki/extensions/UploadWizard"
        - "mediawiki/extensions/UrlShortener"
        - "mediawiki/extensions/UserMerge"
        - "mediawiki/extensions/VipsScaler"
        - "mediawiki/extensions/VisualEditor"
        - "mediawiki/extensions/WebAuthn"
        - "mediawiki/extensions/Wikibase"
        - "mediawiki/extensions/WikibaseCirrusSearch"
        - "mediawiki/extensions/WikibaseLexeme"
        - "mediawiki/extensions/WikibaseLexemeCirrusSearch"
        - "mediawiki/extensions/WikibaseMediaInfo"
        - "mediawiki/extensions/WikibaseQualityConstraints"
        - "mediawiki/extensions/Wikidata.org"
        - "mediawiki/extensions/WikidataPageBanner"
        - "mediawiki/extensions/WikiEditor"
        - "mediawiki/extensions/wikihiero"
        - "mediawiki/extensions/WikiLove"
        - "mediawiki/extensions/WikimediaApiPortalOAuth"
        - "mediawiki/extensions/WikimediaBadges"
        - "mediawiki/extensions/WikimediaEditorTasks"
        - "mediawiki/extensions/WikimediaEvents"
        - "mediawiki/extensions/WikimediaIncubator"
        - "mediawiki/extensions/WikimediaMaintenance"
        - "mediawiki/extensions/WikimediaMessages"
        - "mediawiki/extensions/Wikisource"
        - "mediawiki/extensions/XAnalytics"
        - "mediawiki/skins/CologneBlue"
        - "mediawiki/skins/MinervaNeue"
        - "mediawiki/skins/Modern"
        - "mediawiki/skins/MonoBook"
        - "mediawiki/skins/Nostalgia"
        - "mediawiki/skins/Timeless"
        - "mediawiki/skins/Vector"
        - "mediawiki/skins/WikimediaApiPortal"
        - "mediawiki/vendor"
    wmf_branch:
        - include: "wmf_core"
        - "VisualEditor/VisualEditor"

manual_branch_points:
    REL1_27:
        mediawiki/core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
    REL1_29:
        mediawiki/core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
    REL1_30:
        mediawiki/core: 0cd28e19cb0f9385a2a1cc11a4d8c9c21ff0b830
diff:
    ignore:
        - "*~"
        - ".js*"
        - ".git*"
        - "#*#"
        - ".#*"
        - ".rubocop*"
        - ".travis.yml"
        - "package.json"
        - "messages"
        - "Gemfile*"
        - ".mailmap"
        - "*.png"
        - "*.jpg"
        - "*.xcf"
        - "*.gif"
        - "*.svg"
        - "*.tiff"
        - "*.zip"
        - "*.xmp"
tar:
    ignore:
        - "*~"
        - "#*#"
        - ".*"
        - "package.json"
        - "README.mediawiki"
        - "Gemfile*"
        - "vendor/pear/net_smtp/README.rst"
